stages:
- stage: iOS
  displayName: 'iOS'
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: ios

- stage: iOSSimulator
  displayName: 'iOS Simulator'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: iossim

- stage: macOS
  displayName: 'macOS'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: mac

- stage: macCatalyst
  displayName: 'macCatalyst'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: catalyst

- stage: Android
  displayName: 'Android'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: android
