stages:
- stage: iOS
  displayName: 'iOS'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: ios

- stage: iOSSimulator
  displayName: 'iOS Simulator'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: iossim

- stage: visionOS
  displayName: 'visionOS'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: ios

- stage: visionOSSimulator
  displayName: 'visionOS Simulator'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: visionossim

- stage: macOS
  displayName: 'macOS'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: mac

- stage: macCatalyst
  displayName: 'macCatalyst'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: catalyst

- stage: Android
  displayName: 'Android'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: android

- stage: Emscripten
  displayName: 'Emscripten'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: emscripten
