stages:
- stage: iOS
  displayName: 'iOS'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: ios
      vmImage: macos-14

- stage: iOSSimulator
  displayName: 'iOS Simulator'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: iossim
      vmImage: macos-14

- stage: visionOS
  displayName: 'visionOS'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: visionos
      vmImage: macos-14

- stage: visionOSSimulator
  displayName: 'visionOS Simulator'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: visionossim
      vmImage: macos-14

- stage: macOS
  displayName: 'macOS'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: mac
      vmImage: macos-14

- stage: macCatalyst
  displayName: 'macCatalyst'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: catalyst
      vmImage: macos-14

- stage: Android
  displayName: 'Android'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: android
      vmImage: ubuntu-latest

- stage: Emscripten
  displayName: 'Emscripten'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: emscripten
      vmImage: macos-14
