stages:
- stage: iOS
  displayName: 'iOS'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: ios
      vmImage: macos-15

- stage: iOSSimulator
  displayName: 'iOS Simulator'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: iossim
      vmImage: macos-15

- stage: visionOS
  displayName: 'visionOS'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: visionos
      vmImage: macos-15

- stage: visionOSSimulator
  displayName: 'visionOS Simulator'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: visionossim
      vmImage: macos-15

- stage: macOS
  displayName: 'macOS'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: mac
      vmImage: macos-15

- stage: macCatalyst
  displayName: 'macCatalyst'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: catalyst
      vmImage: macos-15

- stage: Android
  displayName: 'Android'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: android
      vmImage: ubuntu-24.04

- stage: Emscripten
  displayName: 'Emscripten'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: emscripten
      vmImage: macos-15

- stage: XCFramework
  displayName: 'Generate XCFramework'
  dependsOn:
  - iOS
  - iOSSimulator
  - visionOS
  - visionOSSimulator
  - macOS
  - macCatalyst
  jobs:
  - template: jobs/xcframework.yml
    parameters:
      buildTarget: mac
      vmImage: macos-15
