jobs:
- job: Build
  displayName: 'Build'
  pool:
    vmImage: macos-12

  variables:
    buildTarget: ${{ parameters.buildTarget }}

  steps:
  - script: brew install meson wget
    displayName: 'Install Dependencies'

  - script: sh ./download.sh
    displayName: 'Download'

  - script: |
      export NDK=$ANDROID_NDK_HOME
      sh ./build_$(buildTarget).sh
    displayName: 'Build'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(buildTarget)'
      ArtifactName: '$(buildTarget)'
      publishLocation: 'Container'
    displayName: 'Publish'