jobs:
- job: Build
  displayName: 'Build'
  timeoutInMinutes: 120
  pool:
    vmImage: ${{ parameters.vmImage }}

  variables:
    vmImage: ${{ parameters.vmImage }}
    buildTarget: ${{ parameters.buildTarget }}
    xcodeVersion: ${{ '26.0' }}
    ndkVersion: ${{ '28.2.13676358' }}

  steps:
  - script: |
      # Error: cmake was installed from the local/pinned tap
      brew remove cmake || true
      brew untap local/pinned || true
      brew install meson wget cmake zsh yasm tcsh
    displayName: 'Install Dependencies (Mac)'
    condition: contains(variables['vmImage'], 'mac')

  - script: |
      sudo apt-get install meson wget cmake zsh ncompress tcsh gcc-multilib yasm
    displayName: 'Install Dependencies (Ubuntu)'
    condition: contains(variables['vmImage'], 'ubuntu')

  - script: |
      chmod +x download.sh
      ./download.sh
    displayName: 'Download'

  - script: |
      if [ "$(buildTarget)" = "emscripten" ]; then
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
      fi
    displayName: 'Replace Strings'

  - script: |
      if [ "$(buildTarget)" = "emscripten" ]; then
        cd emsdk
        SDK_PATH=$(pwd)
        . ./emsdk_env.sh
        cd ..
      elif [ "$(buildTarget)" = "android" ]; then
        SDK_PATH=$ANDROID_HOME/ndk/$(ndkVersion)
      fi
      if [[ $(vmImage) = *"mac"* ]]; then
        sudo xcode-select -s /Applications/Xcode_$(xcodeVersion).app
        xcodebuild -version
      fi
      chmod +x prepare_icu.sh
      chmod +x build_$(buildTarget).sh
      ./prepare_icu.sh
      ./build_$(buildTarget).sh $(pwd)/$(buildTarget) $SDK_PATH
    displayName: 'Build'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(buildTarget)'
      ArtifactName: '$(buildTarget)'
      publishLocation: 'Container'
    displayName: 'Publish'

  - task: UniversalPackages@0
    inputs:
      command: 'publish'
      publishDirectory: '$(buildTarget)'
      feedsToUsePublish: 'internal'
      vstsFeedPublish: '9f9dcde1-dcba-4537-8214-71c8a03b99a0/14bb1031-e6b2-40ac-b287-73e7fcb5900e'
      vstsFeedPackagePublish: 'celestia-$(buildTarget)-dependencies'
      versionOption: 'patch'
    condition: and(or(eq( variables['buildTarget'], 'ios' ), eq( variables['buildTarget'], 'catalyst' ), eq( variables['buildTarget'], 'android' )), eq(variables['publish'], 'true'))
