jobs:
- job: Build
  displayName: 'Generate XCFramework'
  pool:
    vmImage: ${{ parameters.vmImage }}

  variables:
    xcodeVersion: ${{ '16.4' }}

  steps:
  - script: |
      sudo xcode-select -s /Applications/Xcode_$(xcodeVersion).app
    displayName: 'Select Xcode'

  - task: DownloadBuildArtifacts@0
    displayName: 'Download iOS Artifacts'
    inputs:
      artifactName: 'ios'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - task: DownloadBuildArtifacts@0
    displayName: 'Download iOS Simulator Artifacts'
    inputs:
      artifactName: 'iossim'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - task: DownloadBuildArtifacts@0
    displayName: 'Download visionOS Artifacts'
    inputs:
      artifactName: 'visionos'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - task: DownloadBuildArtifacts@0
    displayName: 'Download visionOS Simulator Artifacts'
    inputs:
      artifactName: 'visionossim'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - task: DownloadBuildArtifacts@0
    displayName: 'Download Mac Artifacts'
    inputs:
      artifactName: 'mac'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - task: DownloadBuildArtifacts@0
    displayName: 'Download Catalyst Artifacts'
    inputs:
      artifactName: 'catalyst'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - script: |
      chmod +x merge_xcframework.sh
      mkdir apple
      ./merge_xcframework.sh $(pwd)/apple $(pwd)
    displayName: 'Build'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'apple'
      ArtifactName: 'apple'
      publishLocation: 'Container'
    displayName: 'Publish'
