name: 'Setup Ubuntu Build Environment'
description: 'Sets up Android NDK, installs dependencies, downloads and prepares ICU for Ubuntu builds'

inputs:
  ndk-version:
    description: 'Android NDK version to use'
    required: false
    default: 'r29'

runs:
  using: 'composite'
  steps:
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: ${{ inputs.ndk-version }}
        add-to-path: false

    - name: Set NDK Environment Variables
      shell: bash
      run: |
        set -e -o pipefail
        echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
        echo "ANDROID_NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
        echo "NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
        echo "Android NDK ${{ inputs.ndk-version }} installed at: ${{ steps.setup-ndk.outputs.ndk-path }}"

    - name: Install Dependencies
      shell: bash
      run: |
        set -e -o pipefail
        sudo apt-get update
        sudo apt-get install meson wget cmake zsh ncompress tcsh gcc-multilib yasm

    - name: Download Dependencies
      shell: bash
      run: |
        set -e -o pipefail
        chmod +x download.sh
        ./download.sh

    - name: Prepare ICU
      shell: bash
      run: |
        set -e -o pipefail
        chmod +x prepare_icu.sh
        ./prepare_icu.sh
