name: Build All Platforms

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g., 1.0). If provided, will create a GitHub release'
        required: false
        default: ''
        type: string
      prerelease:
        description: 'Mark release as prerelease'
        required: false
        default: false
        type: boolean

env:
  VERSION: ${{ inputs.release_version && format('{0}.{1}', inputs.release_version, github.run_number) || '' }}

jobs:
  # Apple platforms
  ios:
    uses: ./.github/workflows/reusable-build.yml
    with:
      platform: ios
      runner: macos-15

  ios-simulator:
    uses: ./.github/workflows/reusable-build.yml
    with:
      platform: iossim
      runner: macos-15

  visionos:
    uses: ./.github/workflows/reusable-build.yml
    with:
      platform: visionos
      runner: macos-15

  visionos-simulator:
    uses: ./.github/workflows/reusable-build.yml
    with:
      platform: visionossim
      runner: macos-15

  macos:
    uses: ./.github/workflows/reusable-build.yml
    with:
      platform: mac
      runner: macos-15

  mac-catalyst:
    uses: ./.github/workflows/reusable-build.yml
    with:
      platform: catalyst
      runner: macos-15

  # Cross-platform builds
  android:
    uses: ./.github/workflows/reusable-build.yml
    with:
      platform: android
      runner: ubuntu-24.04

  emscripten:
    uses: ./.github/workflows/reusable-build.yml
    with:
      platform: emscripten
      runner: macos-15
      setup-emscripten: true

  xcframework:
    name: Generate XCFramework
    runs-on: macos-15
    needs: [ios, ios-simulator, visionos, visionos-simulator, macos, mac-catalyst]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate XCFramework
        uses: ./.github/actions/generate-xcframework

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [android, xcframework]
    if: ${{ github.event.inputs.release_version != '' }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release
        uses: ./.github/actions/create-release
        with:
          tag-name: ${{ env.VERSION }}
          release-name: 'Celestia Dependencies'
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
